edition = "2024"
# format_code_in_doc_comments = true
# imports_granularity = "Crate"
# imports_layout = "HorizontalVertical"
max_width = 100
style_edition = "2024"
use_small_heuristics = "Max"
# wrap_comments = true
